# -*- coding: utf-8 -*-
"""duffin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mLAwO_v89Vn-0dADzgcLFi9vhmDb4JOw
"""

import numpy as np

"""$\dot{x} = y$ \
$\dot{y} = -\delta y- \alpha x - \beta x^3 + \gamma \cos(\omega t)$
"""

# Define the system of ODEs
def duffing_system(t, Y, delta, alpha, beta, gamma, omega):
    # If Y is just a single value, we assume the second value (y) is 0
    if np.isscalar(Y):
        x, y = Y, 0
    else:
        x, y = Y
    dxdt = y
    dydt = -delta*y - alpha*x - beta*x**3 + gamma*np.cos(omega*t)
    return [dxdt, dydt]

if __name__ == "__main__":
    print("")